import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shoppay - Home</title>
        <meta name="description" content="Generated by Create Next App" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>Home page</div>
    </div>
  );
}
